apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-db-pvc
  namespace: groupsapp
spec:
  accessModes:
    - ReadWriteOnce
  
  storageClassName: gp2 
  resources:
    requests:
      storage: 1Gi