apiVersion: v1
kind: Secret
metadata:
  name: groupsapp-secret
  namespace: groupsapp
type: Opaque
stringData:
  SECRET_KEY: super_secret_auth_key
  JWT_SECRET: super_secret_jwt_key

  AUTH_DB_NAME: auth_db
  AUTH_DB_USER: auth_user
  AUTH_DB_PASSWORD: auth_pass
  AUTH_DB_DSN: postgresql://auth_user:auth_pass@auth-db:5432/auth_db?sslmode=disable

  CHAT_DB_NAME: chat_db
  CHAT_DB_USER: chat_user
  CHAT_DB_PASSWORD: chat_pass
  CHAT_DB_DSN: postgresql://chat_user:chat_pass@chat-db:5432/chat_db?sslmode=disable

  REPLICATION_USER: replicator
  REPLICATION_PASSWORD: replicator_pass

  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
